name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWNHOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh -t -i private_key.pem ubuntu@ec2-13-51-193-53.eu-north-1.compute.amazonaws.com "cd test-ci-cd && git pull origin main && cd apps/http-backend && pnpm run build && pm2 restart http && cd ../web && pnpm run build && pm2 restart next-app && cd ../ws-server && pnpm run build && pm2 restart ws"
